apiVerssion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: olpomi-com-tls
spec:
  secretName: olpomi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: olpomi.com
  dnsNames:
    - olpomi.com
    - www.olpomi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
         - olpomi.com
         - www.olpomi.com